insert into tag (id, name, color, event_id) values (1, 'Alphazap', 'Puce', 1);
insert into tag (id, name, color, event_id) values (2, 'Cardguard', 'Red', 2);
insert into tag (id, name, color, event_id) values (3, 'Job', 'Aquamarine', 3);
insert into tag (id, name, color, event_id) values (4, 'Konklab', 'Red', 4);
insert into tag (id, name, color, event_id) values (5, 'Quo Lux', 'Green', 5);
insert into tag (id, name, color, event_id) values (6, 'Prodder', 'Green', 6);
insert into tag (id, name, color, event_id) values (7, 'Viva', 'Fuscia', 7);
insert into tag (id, name, color, event_id) values (8, 'Matsoft', 'Violet', 8);
insert into tag (id, name, color, event_id) values (9, 'Redhold', 'Puce', 9);
insert into tag (id, name, color, event_id) values (10, 'Voltsillam', 'Aquamarine', 10);
insert into tag (id, name, color, event_id) values (11, 'Quo Lux', 'Crimson', 11);
insert into tag (id, name, color, event_id) values (12, 'Latlux', 'Blue', 12);
insert into tag (id, name, color, event_id) values (13, 'Trippledex', 'Purple', 13);
insert into tag (id, name, color, event_id) values (14, 'Trippledex', 'Blue', 14);
insert into tag (id, name, color, event_id) values (15, 'Wrapsafe', 'Maroon', 15);
insert into tag (id, name, color, event_id) values (16, 'Alphazap', 'Pink', 16);
insert into tag (id, name, color, event_id) values (17, 'Fintone', 'Fuscia', 17);
insert into tag (id, name, color, event_id) values (18, 'Wrapsafe', 'Green', 18);
insert into tag (id, name, color, event_id) values (19, 'Sonair', 'Orange', 19);
insert into tag (id, name, color, event_id) values (20, 'Asoka', 'Fuscia', 20);
insert into tag (id, name, color, event_id) values (21, 'Sonsing', 'Indigo', 21);
insert into tag (id, name, color, event_id) values (22, 'Zontrax', 'Yellow', 22);
insert into tag (id, name, color, event_id) values (23, 'Treeflex', 'Fuscia', 23);
insert into tag (id, name, color, event_id) values (24, 'Fix San', 'Puce', 24);
insert into tag (id, name, color, event_id) values (25, 'Treeflex', 'Crimson', 25);
insert into tag (id, name, color, event_id) values (26, 'Daltfresh', 'Turquoise', 26);
insert into tag (id, name, color, event_id) values (27, 'Vagram', 'Goldenrod', 27);
insert into tag (id, name, color, event_id) values (28, 'Quo Lux', 'Indigo', 28);
insert into tag (id, name, color, event_id) values (29, 'Ventosanzap', 'Maroon', 29);
insert into tag (id, name, color, event_id) values (30, 'Zamit', 'Fuscia', 30);
insert into tag (id, name, color, event_id) values (31, 'Stronghold', 'Yellow', 31);
insert into tag (id, name, color, event_id) values (32, 'Mat Lam Tam', 'Purple', 32);
insert into tag (id, name, color, event_id) values (33, 'Gembucket', 'Maroon', 33);
insert into tag (id, name, color, event_id) values (34, 'Lotlux', 'Mauv', 34);
insert into tag (id, name, color, event_id) values (35, 'Voltsillam', 'Khaki', 35);
insert into tag (id, name, color, event_id) values (36, 'Gembucket', 'Red', 36);
insert into tag (id, name, color, event_id) values (37, 'Span', 'Puce', 37);
insert into tag (id, name, color, event_id) values (38, 'Cardify', 'Green', 38);
insert into tag (id, name, color, event_id) values (39, 'Cardguard', 'Khaki', 39);
insert into tag (id, name, color, event_id) values (40, 'It', 'Fuscia', 40);
insert into tag (id, name, color, event_id) values (41, 'Latlux', 'Aquamarine', 41);
insert into tag (id, name, color, event_id) values (42, 'Fixflex', 'Orange', 42);
insert into tag (id, name, color, event_id) values (43, 'Tempsoft', 'Crimson', 43);
insert into tag (id, name, color, event_id) values (44, 'Fintone', 'Purple', 44);
insert into tag (id, name, color, event_id) values (45, 'Gembucket', 'Yellow', 45);
insert into tag (id, name, color, event_id) values (46, 'Otcom', 'Maroon', 46);
insert into tag (id, name, color, event_id) values (47, 'Duobam', 'Puce', 47);
insert into tag (id, name, color, event_id) values (48, 'Span', 'Orange', 48);
insert into tag (id, name, color, event_id) values (49, 'Konklab', 'Violet', 49);
insert into tag (id, name, color, event_id) values (50, 'Fix San', 'Red', 50);
